---
title: "Ci"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(xtable)
library(pander)
```

## Data

```{r echo=FALSE}
# in order to use modelling, need to hypothesize a dose-response fn
A0 = c(0,0,0,0,1,1,1,1)
Z1 = c(0,0,1,1,0,0,1,1)
A1 = c(0,1,0,1,0,1,0,1)
Y = c(87.29, 112.11, 119.65, 144.84, 105.28, 130.18, 137.72, 162.83)
N = c(209271, 93779, 60654, 136293, 134781, 60789, 93903, 210527)
df = data.frame(A0=A0, Z1=Z1, A1=A1, Y=Y, N=N)
kable(df)
```

## Inverse Probability Weighting

```{r echo=FALSE}

tm = glm(A1 ~ Z1, weights = N, family = binomial) # treatment model
tm_sw = glm(A1 ~ 1, weights = N, family = binomial) # treatment model - stabilize weights

sw_num = ifelse(df$A1==1, plogis(coefficients(tm_sw))*.5, (1-plogis(coefficients(tm_sw))) * .5 )

sw_den = ifelse(df$A1 == 1, fitted.values(tm), 1- fitted.values(tm)) * .5

pseudo_N = sw_num/sw_den * N

mod = lm(Y ~ A0 + A1, weights = pseudo_N)
pander(summary(mod))

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
